name: Bug report
description: Found a bug that needs to be fixed?
body:
- type: markdown
  attributes:
    value: |-
      Please join the [discord server](https://discord.gg/mYKK4BwGxe) for questions or ask them in [our discussions](https://github.com/BlockyDotJar/SLF4J-Fallback-Logger/discussions).
      
      Keep in mind that this isn't the place to learn Java.  
      Please head over to [StackOverflow](https://stackoverflow.com/questions/tagged/java) for your general programming questions.
- type: checkboxes
  attributes:
    label: General troubleshooting
    description: You confirm to have made the following checks first.
    options:
      - label: I have checked for similar issues on the Issue-tracker.
        required: true
      - label: I have updated to the [latest SLF4J-fbl version](https://github.com/BlockyDotJar/SLF4J-Fallback-Logger/releases/latest)
        required: true
      - label: I have checked the branches or the maintainer's prs for upcoming bug fixes.
        required: true
- type: textarea
  attributes:
    label: "Expected behaviour"
    description: "What did you expect SLF4J-fbl to do?"
    placeholder: "SFL4J-fbl should do ..."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Code example for reproduction steps"
    description: |-
      Please add the code you use to reproduce this problem.  
      Leave this empty or put "N/A" if you don't have a reproducible setup.
      
      The provided text will be rendered as Java code, so you don't have to provide a code block for it.
    render: Java
    placeholder: |-
      public void causeError() {
          throw new Exception("Error!");
      }
  validations:
    required: true
- type: textarea
  attributes:
    label: "Code for FallbackLogger or/and Logger used"
    description: |-
      Please provide the code used to create your FallbackLogger or/and Logger instance.  
      
      The provided text will be rendered as Java code, so you don't have to provide a code block for it.
    render: Java
    placeholder: 'Logger logger = FallbackLogger.getLog(Main.class)'
  validations:
    required: true
- type: textarea
  attributes:
    label: "Exception or error"
    description: |-
      Share any exception or error you encountered.  
      Make sure to put it into a code block for better formatting.
      Leave this blank or put "N/A" if you don't have an exception or error.
      
      The provided text will be rendered as code, so you don't have to provide a code block for it.
    render: Java
    placeholder: "java.lang.NullPointerException: null"
